### ISSUE TITLE
IS IT ABANDONED? 

### ISSUE THREAD

**Issue by akorchyn** [haski007/workerpool#2]
My huge-ass with a lot of $$$ startup is using this innovative and great library.

BUT I HAVEN"T SEEN ANY UPDATES FROM YOU FOOOOR AGES.

GOD BLESS, I WOULD FIND YOU IF MY HUGE $$$ STARTUP WILL COLLAPSE CAUSE OF YOUR LAZINESS.

START WORKING ON IT

**Comment by dmlitvin** [comment]
totally agree

**Comment by haski007** [comment]
It works pretty well, updates aren't really needed
